name: ci

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
        env:
          HUSKY: 0
      - run: pnpm run db:generate
      - run: test -z "$(git status --porcelain)"
      - run: pnpm run check:lint
      - run: pnpm run check:format
      - run: pnpm run check:types
